name: Appimage Create Release Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      shell: bash
      run: ./configure.sh --release
      
    - name: make
      run: make appimage-bld/osc-tui-x86_64.AppImage
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "v22.09.0"
          prerelease: false
          title: "Fix Release"
          files: |
            LICENSE
            appimage-bld/osc-tui-x86_64.AppImage
